### ISSUE TITLE
Any plans on including "file" as dependency?

### ISSUE THREAD

**Issue by cactusnoh** [wummel/patool#146]
Hi, I've recently noticed that some "slim" linux docker images don't include "file" out of the box.
This seems to have an impact on some files that are mistyped (ex. a zip file may be mistyped to be gz file by altering its name).
Since patool uses "file" tool to figure out which kind of archive the file is.
After installing "file" in the docker container, the problem seems to go away.
So my personal thought is that including "file" as dependency will reduce unexpected bugs of this sort.

file: https://darwinsys.com/file/

**Comment by harkabeeparolus** [comment]
This is more of an issue for various OS platforms. Those who make OS packages (.deb or .rpm) of patool should certainly include file as a dependency, or at least a recommended package. There is little patool could do other than document this and recommend it to downstream packagers. Since the standard file utility isn't written in Python, it is not on PyPI, and we couldn't add it as a direct dependency.

Please note that "file" is a POSIX standard utility, and therefore it's expected to exist on normal Unix operating systems.
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/file.html

**Comment by cactusnoh** [comment]
> This is more of an issue for various OS platforms. Those who make OS packages (.deb or .rpm) of patool should certainly include file as a dependency, or at least a recommended package. There is little patool could do other than document this and recommend it to downstream packagers. Since the standard file utility isn't written in Python, it is not on PyPI, and we couldn't add it as a direct dependency.
> 
> Please note that "file" is a POSIX standard utility, and therefore it's expected to exist on normal Unix operating systems. https://pubs.opengroup.org/onlinepubs/9699919799/utilities/file.html

Yes, I think a specification in the documentation will do just fine :)

**Comment by cactusnoh** [comment]
Nvm there is already a statement about "file"
