### ISSUE TITLE
patool doesn't create usable patool.bat/.exe on windows

### ISSUE THREAD

**Issue by yarikoptic-private** [wummel/patool#21]
running pip install patool (within virtualenv) does create patool   python script (without .py extension) which is useless on windows since what is needed is an obscure .exe which would call into that script.  So far the most straightforward way to generate such .exe files I found is to use machinery available within setuptools and which it provides for `entry_points`, see e.g. primitive setup.py of ours:  https://github.com/yarikoptic/datalad/blob/nf-custom-remotes/setup.py#L30  where we tell it to create two cmdline scripts invoking two different cmdline handlers.

Unfortunately patool's setup.py is too evolved for me to provide any complete recipe here, if only I knew more why inno scripts etc.

Cheers

**Comment by wummel** [comment]
Well, py2exe is deprecated. Its on the todo list to switch to pyinstaller instead but this will take some time.

**Comment by cgmb** [comment]
I was actually going to ask about this, because it seemed fairly simple to me. I just followed [Sharing Your Labor of Love: PyPI Quick and Dirty](https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/) and the result 'just worked' on Windows.

I'm not entirely sure how the exe was created (because I certainly did not build on Windows), but I could pip install [my utility](https://github.com/cgmb/d2lmf) and the exe would be there.

In any case, it looks like you're addressing this in your recent commits. Thanks for building such a handy tool.

**Comment by wummel** [comment]
the new wheel (.whl) installer file which replaces the .exe installer fixes this
