### ISSUE TITLE
patool and Python 3 

### ISSUE THREAD

**Issue by eirnym** [wummel/patool#25]
As I've read on PyPI you doesn't support Python3 (no classifiers for that). On the site you say that patool have support for specific versions of Python.

Please, update classifiers

**Comment by wummel** [comment]
We believe that the issue you reported is fixed in the source repository of patool which can be found under:
https://github.com/wummel/patool

Changelog entry:
* Updated PyPI trove classifiers to include Python 3
  Closes: GH bug #25

Thank you for reporting the issue. It is now marked as fixed. If you believe that the issue is not fixed appropriately just add a comment to this issue.

**Comment by wummel** [comment]
A new version 1.9 of patool has been released on 07.12.2015.
Therefore this bug will be closed. If you think this issue is not solved, please open a new issue.

**Comment by eirnym** [comment]
Thank you!
