### ISSUE TITLE
Return an iterator with list_archive

### ISSUE THREAD

**Issue by h5rdly** [wummel/patool#44]
Hi,

First of all, great library, thank you.

I have a question regarding list_archive(). It lists the archive contents directly to stdout. To use the output, sys.stdout needs to be captured by some means of redirection and restoring. 

Is it possible to perhaps have it return an iterator instead or in addition to the sys.stdout() output? 

Edit: A tuple would be great too.

**Comment by wummel** [comment]
Since patool relies on other applications to list archives, a structured output would need to parse text into filename lists. This is not planned since it is not supported by those applications. If you need this, use the available compression modules (eg. zipfile) in Python directly, or parse the output in a custom script suited for your individual case.
