### ISSUE TITLE
file `D' was not found

### ISSUE THREAD

**Issue by muhammedfurkan** [wummel/patool#79]
how can I fix that

**Comment by yarikoptic** [comment]
Bug wasn't found, closing.

On a serious note - provide details, eg how we could replicate and what version of patool you are using

**Comment by wummel** [comment]
Closing, if you still have problems with a newer version of patool you can file a new issue.

**Comment by Mips96** [comment]
I had the same issue with `create_archive()`. The problem is that the second parameter (the list of files/folders that should be zipped) can be in a tuple as indicated in the readme _if_ there are multiple files/folders. But if you try to zip only one file, it has to be in a list. Otherwise, you get an error along the lines of `file [the first letter of your filename] was not found`, which in OP's case was D. This is also referred to in issue #123.
